### ISSUE TITLE
Addon disables subtitles on new episode

### ISSUE THREAD

**Issue by cripticcorp** [Dreamlinerm/Netflix-Prime-Auto-Skip#16]
Add-on disables subtitles, initially it works fine but after Amazon moves to the next episode subtitles fail to appear and I need to refresh the page and go back into that episode or disable then re-enable subtitles. 
This is still better than having to watch trailers for amazon prime material between episodes (on a service i pay for) but it would be nice if its easily fixable.

**Comment by Dreamlinerm** [comment]
@cripticcorp Trying to replicate the issue today and see if I can fix it.

**Comment by Dreamlinerm** [comment]
I didn't watch anything with subtitles on Amazon Prime, that's why it definitely hasn't occurred to me yet.

**Comment by Dreamlinerm** [comment]
@cripticcorp which browser are you using on Firefox, there doesn't seem to be a problem. I'm checking chrome now

**Comment by Dreamlinerm** [comment]
@cripticcorp if the problems continue, I would recommend going to the individual settings of the Prime Video Auto-skips and turning off credits in the settings (that could fix the issue).

**Comment by Dreamlinerm** [comment]
@cripticcorp if you want to show me how the issue occurs, here's my discord handle: Dreamliner#0104
I cant seem to replicate it on my own, maybe, it's because of a slow internet connection?

**Comment by Dreamlinerm** [comment]
I managed to see the issue for myself and now need to find out whats causing it.

**Comment by Dreamlinerm** [comment]
Fixed in c6f996bee355536bf35025814d7b54299dc3ee97

**Comment by yannprada** [comment]
Hello, I have version 1.0.14, and the issue still occurs, I have to disable / enable subtitles

**Comment by Dreamlinerm** [comment]
really, it fixed it for me maybe can you give me more information, like which browser or when it occurs

**Comment by yannprada** [comment]
Firefox
Funny thing, it works now, but I didn't change anything, and no updates that I know of

**Comment by Dreamlinerm** [comment]
> 
I am using Firefox as well, I thought I fixed the issue, by waiting for the video to load, but maybe I have to set a larger tolerance. Keep me updated

**Comment by Dreamlinerm** [comment]
In my latest update, the infinite loading and subtitle issue should hopefully be resolved. If you have any problems, keep me posted

**Comment by yannprada** [comment]
Thanks, seems OK so far, but I'll be sure to let you know

**Comment by Dreamlinerm** [comment]
Have been watching series, I'm closing the issues until more reports
